# Data transformation

Our dataset was heavily pre-processed by the researchers at the Pew Research Center and so very little data transformation was required for our project. We primarily relied on grouping and filtering the dataset based on characteristics of interest for each of our questions. 

The only true data transformation that took place was our creation of a Language Proficiency column to answer a section of Question 3. This was done as follows:

- We first selected the columns of interest. In this case, we limited our understanding of being proficient at a language to whether the respondent could carry on a conversation in English and Spanish well. Information regarding this was found in columns 'LAN1_W58' for Spanish and 'LAN3_W58' for English. 
- Created a new column 'LANPROF' to encode language proficiency as Bilingual, Spanish, or English. 
- Filled out column 'LANPROF' with the following definitions:
  - Bilingual if (LAN1_W58 == 'Pretty well' | LAN1_W58 == 'Very well') & (LAN3_W58 == 'Pretty well' | LAN3_W58 == 'Very well')
  - Spanish if (LAN1_W58 == 'Pretty well' | LAN1_W58 == 'Very well') & (LAN3_W58 == 'Just a little' | LAN3_W58 == 'Not at all')
  - English if (LAN1_W58 == 'Just a little' | LAN1_W58 == 'Not at all') & (LAN3_W58 == 'Pretty well' | LAN3_W58 == 'Very well')
- Lastly, we filtered our any possible NA values present. 

