# Results



# Data sources


```{r}
library(haven)
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(networkD3)
library(leaflet)
dataset = read_sav("ATP W58.sav")
```




```{r}


dataset2 <-  dataset[ , c(1,8,10,11,12,13,14,15,16,17,18,19,21,22,23,32,39,40,41,42,43,44,49,50,51,52,63,64,65,66,67,69,70,71,72,73,74,75,78,79,80,81,82,83,84,85,86,87,88,89,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,110)]

library(tidyverse)
library(dplyr)

ds= as_factor(dataset2)
dataset3 = ds[ , c("F_PARTY_FINAL","YEARSINUS_W58")]

financial_set = dataset2[ , c("F_PARTY_FINAL","HISPORIGCMB_W58","PERSFIN_W58","LAN1_W58","LAN3_W58","IDENSAL_a_W58","IDENSAL_b_W58","IDENSAL_d_W58","IDENSAL_e_W58","IDENSAL_f_W58")]

financial_set <- financial_set %>% filter(LAN1_W58+LAN3_W58 <=6)
financial_set <- financial_set %>% filter(IDENSAL_b_W58 <90)

#cor(financial_set)




# financial_set$F_PARTY_FINAL <- as_factor(financial_set$F_PARTY_FINAL)
# financial_set$YEARSINUS_W58 <- as_factor(financial_set$YEARSINUS_W58)
# financial_set$HISPORIGCMB_W58 <- as_factor(financial_set$HISPORIGCMB_W58)






# PUERTO RICO counted here as outside US

dataset3  <- dataset3 %>%
     mutate(YEARSINUS_W58 = ifelse(is.na(YEARSINUS_W58),"Not Born in US","Born in US"))

# ggplot(dataset3, aes(x=F_PARTY_FINAL)) +
#   geom_histogram(stat = "count", position = "dodge", freq = TRUE)


# ggplot(dataset3, aes(x=YEARSINUS_W58, fill=F_PARTY_FINAL)) +
#   geom_histogram(stat = "count", position = "dodge", freq = TRUE)

grouped_data <- aggregate(dataset3, by=list(dataset3$F_PARTY_FINAL, dataset3$YEARSINUS_W58), FUN=length)
# can add column with colors and scale_fill_identity()
# build democrat and republican profiles based on views and combine

grouped_data <- subset(grouped_data, select = -F_PARTY_FINAL)
grouped_data <- grouped_data %>% pivot_wider(names_from = "Group.2", values_from = YEARSINUS_W58)

grouped_data$`Not Born in US` <- grouped_data$`Not Born in US`/sum(grouped_data$`Not Born in US`)
grouped_data$`Born in US` <- grouped_data$`Born in US`/sum(grouped_data$`Born in US`)

grouped_data <- grouped_data %>% pivot_longer(!Group.1, names_to = "Birthplace", values_to = "Percent")

grouped_data <- arrange(grouped_data, -Percent)


dataset3$F_PARTY_FINAL <- factor(dataset3$F_PARTY_FINAL, levels = c("Democrat", "Republican", "Independent", "Something else", NA))




# ggplot(data=dataset3, aes(x=F_PARTY_FINAL, y=..count.., fill = factor(..x..))) +
#   geom_bar(stat="count") + scale_fill_manual(values=c("#0015BC", "#FF0000", "Purple","Brown","Yellow"))+
#     labs(y = "Percent", x = "Party", fill="Party")




dataset3 %>% 
  count(F_PARTY_FINAL) %>% 
  mutate(perc = n / nrow(dataset3)) -> temp

ggplot(temp, aes(x = F_PARTY_FINAL, y = perc, fill = factor(..x..))) + geom_bar(stat = "identity") + scale_y_continuous(labels=scales::percent) +
    labs(y = "Percent", x = "Party", fill="Party")  +
    geom_text(aes(label = sprintf("%1.2f%%", 100*perc), vjust = -0.2))+ scale_fill_manual(values=c("#0015BC", "#FF0000", "Grey","Grey","Grey"))



ggplot(dataset3, aes(F_PARTY_FINAL, group = YEARSINUS_W58)) + geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", x = "Party", fill="Party") +
    facet_grid(~YEARSINUS_W58) +
    scale_y_continuous(labels = scales::percent)+ scale_fill_manual(values=c("#0015BC", "#FF0000", "Grey","Grey","Grey"))







dataset4 = ds[ , c("F_PARTY_FINAL","YEARSINUS_W58","HISPORIGCMB_W58")]

dataset4  <- dataset4 %>%
     mutate(YEARSINUS_W58 = ifelse(is.na(YEARSINUS_W58),"Not Born in US","Born in US"))






dataset5 = ds[ , c("PERSFIN_W58","HISPORIGCMB_W58")]
data_long <- aggregate(dataset5, by=list(dataset5$PERSFIN_W58, dataset5$HISPORIGCMB_W58), FUN=length)


dataset6 = ds[ , c("F_PARTY_FINAL","PERSFIN_W58")]
data_long2 <- aggregate(dataset6, by=list(dataset6$F_PARTY_FINAL, dataset6$PERSFIN_W58), FUN=length)

data_long <- subset (data_long, select = -HISPORIGCMB_W58)
data_long2 <- subset (data_long2, select = -F_PARTY_FINAL)

data_long <- rbind(data_long,data_long2)

names(data_long)[1] <- 'target'
names(data_long)[2] <- 'source'
names(data_long)[3] <- 'value'

nodes <- data.frame(name=c(as.character(data_long$source), as.character(data_long$target)) %>% unique())

data_long$IDsource=match(data_long$source, nodes$name)-1 
data_long$IDtarget=match(data_long$target, nodes$name)-1


ColourScal ='d3.scaleOrdinal() .range(["#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","#1d8a0f","Black","#FF0000","#0015BC"])'

sankeyNetwork(Links = data_long, Nodes = nodes,
                     Source = "IDsource", Target = "IDtarget",
                     Value = "value", NodeID = "name", 
                     sinksRight=TRUE, colourScale=ColourScal, nodeWidth=40, fontSize=13, nodePadding=20)


# 
# fin_set <- financial_set %>% filter(!(is.na(YEARSINUS_W58)))
# hist(as.numeric(fin_set$YEARSINUS_W58))


```
