# Conclusion

As mentioned in previous chapters, the main limitation of our research was the nature of the data. Since all information was collected thorough a survey we only had access to categorical data. This limited the visualizations we could use and also led to somewhat simplified results. An example of this could be found on the analysis of economic health on political preference found on Question 1. We only had access to a self-reported grading from 'In excellent shape' to 'In poor shape'. It would have been great to instead have access to data indicating the actual income levels of respondents rather than vague, poorly defined, definitions of economic health. 

Another limitation was the fact that the survey only included adults over 18 years old in its target population. A lot of our questions dealt with the question of what constitutes the Latin American experience and excluding such a connected and active part of the Latin American population presented a very limited view of Latin American views of identity and political preferences. We wouldn't be surprised if younger Latinos were much more aware of gender-neutral terms to describe their identity and more open to different interpretations of what it means to be a Latino. 

Exploring the views of younger Latinos would be a great topic for future research. Moreover, pointed out on the last sections of Question 3, more research exploring what Latinos believe is an important aspect of their identity would open the path for a more holistic, and much less simplistic, understanding of their political preferences and embitions.   