--- 
title: "Latinx Political Identity"
author: "Adrian Garcia Hernandez, Mendel Branover"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
--- 
title: "Latinx Political Identity"
author: "Adrian Garcia Hernandez, Mendel Branover"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# Introduction

test text

<!--chapter:end:index.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Data sources


<!--chapter:end:02-data.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Data transformation

<!--chapter:end:03-cleaning.Rmd-->


# Missing values

Placeholder



<!--chapter:end:04-missing.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Results

```{r}
#Setup
library(tidyverse)
library(patchwork)
library(vcd)
```


```{r}
#Inital Data exploration
#3030 observations of 110 variables 
library(haven)
dataset = read_sav("ATP W58.sav")

dataset2 <-  dataset[ , c(1,8,10,11,12,13,14,15,16,17,18,19,21,22,23,32,39,40,41,42,43,44,49,50,51,52,63,64,65,66,67,69,70,71,72,73,74,75,78,79,80,81,82,83,84,85,86,87,88,89,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,110)] 

ds= as_factor(dataset2)
#Age distribution

ggplot(ds, aes(F_AGECAT)) + 
  geom_bar(color = "grey50", fill = "lightblue", width = 1) + theme_grey(16)

```



```{r}
#Initial Data exploration for Question 2: Does experiencing discrimination based on ethnic identity lead to more liberal political views? For example, do people who have experienced discrimination more easily embrace gender-neutral ways of expressing the Latin experience?

```
```{r}
#Graph of discrimination versus party preference 
mosaic(F_PARTY_FINAL ~ HISPDISCR_c_W58,
       data = ds,
       direction = c("v", "h"),
       highlighting_fill = RColorBrewer::brewer.pal(3, "Blues"),
       spacing = spacing_equal(sp = unit(0, "lines")),
       labeling = labeling_border(rot_labels = c(0, 0, 0, 0),
                                  set_varnames = c(HISPDISCR_c_W58 = "Have you been discriminated against?", F_PARTY_FINAL = "Party\nPreference"))) +
  theme_grey(16)
```

```{r}
#Graph of people who have heard term Latinx
ggplot(ds, aes(LATINX1_W58)) + 
  geom_bar(color = "grey50", fill = "lightblue", width = 1) + 
  ylab("Count") + 
  xlab("Response") +
  ggtitle("Have you heard of the term 'Latinx'?") +
  theme_grey(16)

```

```{r}
#Of those who have heard of the term Latinx:
#Note: Still need to filter by people who have heard of Latinx before

#discriminated agains vs. Latinx usage
mosaic(LATINX3_W58 ~ HISPDISCR_c_W58,
       data = ds,
       direction = c("v", "h"),
       highlighting_fill = RColorBrewer::brewer.pal(3, "Blues"),
       spacing = spacing_equal(sp = unit(0, "lines")),
       labeling = labeling_border(rot_labels = c(0, 0, 0, 0),
                                  set_varnames = c(HISPDISCR_c_W58 = "Have you been discriminated against?", LATINX3_W58 = "Latinx\nUsage"))) +
  theme_grey(16)

#discriminated against vs belief that Latinx should be used to describe the latino population

mosaic(LATINX4_W58 ~ HISPDISCR_c_W58,
       data = ds,
       direction = c("v", "h"),
       highlighting_fill = RColorBrewer::brewer.pal(3, "Blues"),
       spacing = spacing_equal(sp = unit(0, "lines")),
       labeling = labeling_border(rot_labels = c(0, 0, 0, 0),
                                  set_varnames = c(HISPDISCR_c_W58 = "Have you been discriminated against?", LATINX4_W58 = "Should Latinx\n be usaged?"))) +
  theme_grey(16)
```


<!--chapter:end:05-results.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Interactive component



<!--chapter:end:06-interactive.Rmd-->

```{r include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```
# Conclusion


<!--chapter:end:07-conclusion.Rmd-->

